apiVersion: apps/v1
kind: Deployment
metadata:
  name: cep-python-main
  namespace: cep
  labels:
    app: cep-python
    k8s: cep-python-main
    env: test
spec:
  selector:
    matchLabels:
      k8s: cep-python-main
  template:
    metadata:
      labels:
        app: cep-python
        k8s: cep-python-main
        env: test
    spec:
      containers:
      - name: cep-python-main
        image: pedromcpimentel/cep-python-base:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        command: ["python3", "main.py"]
        ports:
        - containerPort: 5000
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        envFrom:
          - configMapRef:
              name: cep-cm
          - secretRef:
              name: cep-secret

