apiVersion: v1
kind: Service
metadata:
  name: cep-python-list-csv-svc
  namespace: cep
  labels:
    app: cep-python
    k8s: cep-python-list-csv
    env: test
spec:
  externalIPs:
    - "192.168.49.2"
  ports:
  - port: 5003
    protocol: TCP
    targetPort: 5003
  selector:
    k8s: cep-python-list-csv
  sessionAffinity: None
  type: ClusterIP
